/// Flutter icons FlutterIconCom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIconCom
///      fonts:
///       - asset: fonts/FlutterIconCom.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FlutterIconCom {
  FlutterIconCom._();

  static const _kFontFam = 'FlutterIconCom';
  static const String _kFontPkg = null;

  static const IconData bubble_speak =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData responsive =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resume =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone_cropped =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone_original =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_is_money =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
